global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pollution_prediction_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8000']
        labels:
          service: 'pollution_prediction_app'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus' 